import { Archive, Bot, CheckCircle2, FileText, Pencil, Star } from "lucide-react";
import { getColorValue, HTMLContainer, stopEventPropagation, useColorMode, useEditor, useIsEditing } from "tldraw";
import type { IdeaCardMeta, IdeaCardShape } from "./schema";
import { CARD_INK_DARK, CARD_INK_LIGHT, LOW_CONFIDENCE_AMBER } from "./styles";
import { CardLinkChip, CardLinkEditor, IssueLinkChip } from "./chips";
import { ideaCardPresentation, type IdeaCardPresentation } from "./presentation";
import "./idea-card.css";

interface CardHeaderProps {
  presentation: IdeaCardPresentation;
  onToggleStar: (event: React.SyntheticEvent) => void;
}

function CardHeader({ presentation, onToggleStar }: CardHeaderProps): React.JSX.Element {
  return (
    <header className="as-card-header">
      <div className="as-card-labels" aria-label="Card details">
        {presentation.provenanceLabel ? (
          <span className="as-card-provenance" title="Generated by AI">
            <Bot aria-hidden size={12} strokeWidth={2.2} />
            {presentation.provenanceLabel}
          </span>
        ) : null}
        {presentation.kindLabel ? (
          <span className={`as-card-kind${presentation.isKindlessNote ? " is-note" : ""}`}>
            {presentation.isKindlessNote ? <FileText aria-hidden size={11} strokeWidth={2} /> : null}
            {presentation.kindLabel}
          </span>
        ) : null}
        {presentation.done ? (
          <span className="as-card-state is-done">
            <CheckCircle2 aria-hidden size={12} strokeWidth={2.2} />
            Done
          </span>
        ) : null}
        {presentation.superseded ? (
          <span className="as-card-state">
            <Archive aria-hidden size={12} strokeWidth={2} />
            Superseded
          </span>
        ) : null}
        {presentation.editedByUser ? (
          <span className="as-card-state">
            <Pencil aria-hidden size={11} strokeWidth={2} />
            Edited
          </span>
        ) : null}
      </div>
      <button
        type="button"
        className={`as-card-star${presentation.starred ? " is-starred" : ""}`}
        title={presentation.starred ? "Unstar this card" : "Star this card"}
        aria-label={presentation.starred ? "Unstar this card" : "Star this card"}
        aria-pressed={presentation.starred}
        onPointerDown={stopEventPropagation}
        onClick={onToggleStar}
      >
        <Star aria-hidden size={15} strokeWidth={2} fill={presentation.starred ? "currentColor" : "none"} />
      </button>
    </header>
  );
}

interface CardContentProps {
  editing: boolean;
  title: string;
  body: string;
  onEdit: (patch: Partial<Pick<IdeaCardShape["props"], "title" | "body">>) => void;
}

function CardContent({ editing, title, body, onEdit }: CardContentProps): React.JSX.Element {
  if (editing) {
    return (
      <div className="as-card-content">
        <textarea
          autoFocus
          rows={1}
          className="as-card-edit as-card-title-edit"
          aria-label="Card title"
          value={title}
          placeholder="Title"
          onPointerDown={stopEventPropagation}
          onChange={(event) => onEdit({ title: event.target.value })}
        />
        <textarea
          className="as-card-edit as-card-body-edit"
          aria-label="Card body"
          value={body}
          placeholder="Add detail…"
          onPointerDown={stopEventPropagation}
          onChange={(event) => onEdit({ body: event.target.value })}
        />
      </div>
    );
  }

  return (
    <div className="as-card-content">
      <div className="as-card-title">{title}</div>
      {body ? <div className="as-card-body">{body}</div> : null}
    </div>
  );
}

interface CardFooterProps {
  shape: IdeaCardShape;
  presentation: IdeaCardPresentation;
  editing: boolean;
  accent: string;
  onRemoveLink: (url: string) => void;
}

function CardFooter({ shape, presentation, editing, accent, onRemoveLink }: CardFooterProps): React.JSX.Element {
  return (
    <footer className="as-card-footer">
      {presentation.score ? (
        <div className="as-card-metrics" aria-label="AI triage scores">
          <span className="as-card-chip as-card-metric" title={`Impact ${presentation.score.impact}/5 (AI triage)`}>
            <span>Impact</span>
            <strong>{presentation.score.impact}</strong>
          </span>
          <span className="as-card-chip as-card-metric" title={`Effort ${presentation.score.effort}/5 (AI triage)`}>
            <span>Effort</span>
            <strong>{presentation.score.effort}</strong>
          </span>
          {presentation.score.confidence != null ? (
            <span
              className={`as-card-chip as-card-metric${presentation.lowConfidence ? " is-low-confidence" : ""}`}
              title={`Confidence ${presentation.score.confidence}/5 (AI triage)${presentation.lowConfidence ? " — low, treat as tentative" : ""}`}
              style={
                presentation.lowConfidence
                  ? ({ "--as-chip-accent": LOW_CONFIDENCE_AMBER } as React.CSSProperties)
                  : undefined
              }
            >
              <span>{presentation.lowConfidence ? "Low confidence" : "Confidence"}</span>
              <strong>{presentation.score.confidence}</strong>
            </span>
          ) : null}
        </div>
      ) : null}
      {presentation.issueLinks.map((link) => (
        <IssueLinkChip key={link.url} link={link} accent={accent} />
      ))}
      {presentation.cardLinks.map((link) => (
        <CardLinkChip
          key={link.url}
          link={link}
          accent={accent}
          editing={editing}
          onRemove={() => onRemoveLink(link.url)}
        />
      ))}
      {editing ? <CardLinkEditor shape={shape} accent={accent} /> : null}
    </footer>
  );
}

/** The single semantic Signal renderer mounted by tldraw for every idea-card shape. */
export function IdeaCardBody({ shape }: { shape: IdeaCardShape }): React.JSX.Element {
  const editor = useEditor();
  const colorMode = useColorMode();
  const isEditing = useIsEditing(shape.id);
  const { title, body, origin, superseded, color } = shape.props;
  const colors = editor.getCurrentTheme().colors[colorMode];
  const swatch = superseded ? "grey" : color;
  const tint = getColorValue(colors, swatch, "semi");
  const accent = getColorValue(colors, swatch, "solid");
  const text = colorMode === "dark" ? CARD_INK_DARK : CARD_INK_LIGHT;
  const meta = shape.meta as IdeaCardMeta;
  const presentation = ideaCardPresentation(shape.props, meta, isEditing);

  const removeLink = (url: string) => {
    const links = (meta.links ?? []).filter((link) => link.url !== url);
    editor.updateShape({ id: shape.id, type: "idea-card", meta: { ...shape.meta, links } });
  };

  const toggleStar = (event: React.SyntheticEvent) => {
    stopEventPropagation(event);
    editor.updateShape({
      id: shape.id,
      type: "idea-card",
      meta: { ...shape.meta, starred: !presentation.starred }
    });
  };

  const edit = (patch: Partial<Pick<IdeaCardShape["props"], "title" | "body">>) => {
    const stampEdited = origin === "ai" && !presentation.editedByUser;
    editor.updateShape({
      id: shape.id,
      type: "idea-card",
      props: patch,
      ...(stampEdited ? { meta: { ...shape.meta, editedByUser: true } } : {})
    });
  };

  return (
    <HTMLContainer
      role="article"
      aria-label={title || "Untitled idea"}
      className={`as-idea-card${superseded ? " is-superseded" : ""}${presentation.done ? " is-done" : ""}${isEditing ? " is-editing" : ""}`}
      style={
        {
          width: shape.props.w,
          height: shape.props.h,
          "--as-card-accent": accent,
          "--as-card-tint": tint,
          "--as-card-ink": text
        } as React.CSSProperties
      }
    >
      <CardHeader presentation={presentation} onToggleStar={toggleStar} />
      <CardContent editing={isEditing} title={title} body={body} onEdit={edit} />
      {presentation.showFooter ? (
        <CardFooter
          shape={shape}
          presentation={presentation}
          editing={isEditing}
          accent={accent}
          onRemoveLink={removeLink}
        />
      ) : null}
    </HTMLContainer>
  );
}
